name = "SBPOps"
uuid = "53e2d180-00a8-4b9f-aa62-0b938032b710"
authors = ["tretyak-ilya"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
